#!/bin/sh
set -e

case "$1" in
    purge)
        rm -f /etc/default/printer-service
        if [ -e /usr/share/debconf/confmodule ]; then
            . /usr/share/debconf/confmodule
            db_purge || true
        fi
        ;;
esac

#DEBHELPER#
